# Generated by Django 3.1.3 on 2020-12-02 13:05

from django.db import migrations, models
import elegislative_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('key_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/', validators=[elegislative_app.models.file_validator_image])),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('m_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(choices=[('None', 'None'), ('Secretary to the city council', 'Secretary to the city council'), ('Asst. Secretary to the city council', 'Asst. Secretary to the city council'), ('Administrativ Division', 'Administrativ Division'), ('Agenda & Briefinf Division', 'Agenda & Briefinf Division'), ('Journal & Briefing Division', 'Journal & Briefing Division'), ('Legal Division', 'Legal Division'), ('Majority Floor Leader', 'Majority Floor Leader'), ('Asst. Majority Floor Leader', 'Asst. Majority Floor Leader'), ('Standing Committees', 'Standing Committees'), ('City Councilors', 'City Councilors'), ('Office of the city council of manila', 'Office of the city council of manila'), ('Vice-Mayor & Presiding Officer', 'Vice-Mayor & Presiding Officer'), ('City Mayor', 'City Mayor'), ('Adminisrator', 'Adminisrator')], default='None', max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
