# Generated by Django 3.1.2 on 2021-01-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0005_mommodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordinancemodel',
            old_name='ordinance_fk',
            new_name='agenda_fk',
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('None', 'None'), ('Secretary to the city council', 'Secretary to the city council'), ('Asst. Secretary to the city council', 'Asst. Secretary to the city council'), ('Administrative Division', 'Administrative Division'), ('Agenda & Briefinf Division', 'Agenda & Briefinf Division'), ('Journal & Briefing Division', 'Journal & Briefing Division'), ('Legal Division', 'Legal Division'), ('Majority Floor Leader', 'Majority Floor Leader'), ('Asst. Majority Floor Leader', 'Asst. Majority Floor Leader'), ('Standing Committees', 'Standing Committees'), ('City Councilors', 'City Councilors'), ('Office of the city council of manila', 'Office of the city council of manila'), ('Vice-Mayor & Presiding Officer', 'Vice-Mayor & Presiding Officer'), ('City Mayor', 'City Mayor'), ('Adminisrator', 'Adminisrator')], default='None', max_length=100),
        ),
    ]
