# Generated by Django 3.1.2 on 2021-01-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0006_auto_20210113_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsReccomendationResolutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('commentor_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_resolution_fk', to=settings.AUTH_USER_MODEL)),
                ('resolution_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_fk', to='elegislative_app.resolutionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsReccomendationOrdinanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('commentor_ordiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_ordiance_fk', to=settings.AUTH_USER_MODEL)),
                ('ordinance_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_fk', to='elegislative_app.ordinancemodel')),
            ],
        ),
    ]
