# Generated by Django 3.1.2 on 2021-01-13 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elegislative_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0007_commentsreccomendationordinancemodel_commentsreccomendationresolutionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsRecomendationOrdinanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('commentor_ordiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_ordiance_fk', to=settings.AUTH_USER_MODEL)),
                ('ordinance_comments_recomendation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_comments_recomendation_fk', to='elegislative_app.ordinancemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsRecomendationResolutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('commentor_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_resolution_fk', to=settings.AUTH_USER_MODEL)),
                ('resolution_comments_recommendation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_comments_recommendation_fk', to='elegislative_app.resolutionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeReportOrdinanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='None', max_length=100)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('hard_copy', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[elegislative_app.models.file_validator_pdf], verbose_name='hard copy')),
                ('content', models.TextField()),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('ordinance_committee_report_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_committee_report_fk', to='elegislative_app.ordinancemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeReportResolutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='None', max_length=100)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('hard_copy', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[elegislative_app.models.file_validator_pdf], verbose_name='hard copy')),
                ('content', models.TextField()),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('resolution_committee_report_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_committee_report_fk', to='elegislative_app.resolutionmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentsreccomendationresolutionmodel',
            name='commentor_resolution',
        ),
        migrations.RemoveField(
            model_name='commentsreccomendationresolutionmodel',
            name='resolution_fk',
        ),
        migrations.DeleteModel(
            name='CommentsReccomendationOrdinanceModel',
        ),
        migrations.DeleteModel(
            name='CommentsReccomendationResolutionModel',
        ),
    ]
