# Generated by Django 3.1.2 on 2021-01-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0009_announcementmodel_notificationsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinancemodel',
            name='veto_message',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
