# Generated by Django 3.1.2 on 2021-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0010_ordinancemodel_veto_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
