# Generated by Django 3.1.2 on 2021-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0011_announcementmodel_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsmodel',
            name='tags',
            field=models.CharField(choices=[('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None'), ('None', 'None')], default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='notificationsmodel',
            name='url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
