# Generated by Django 3.1.2 on 2021-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0015_auto_20210128_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_overall',
            field=models.BooleanField(default=False, verbose_name='Manage through all records.'),
        ),
    ]
