# Generated by Django 3.1.5 on 2021-01-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0017_auto_20210128_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolutionmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
