# Generated by Django 3.1.5 on 2021-01-29 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0018_auto_20210128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeereportordinancemodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committeereportresolutionmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mommodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordinancemodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='committeereportordinancemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cro_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committeereportresolutionmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crr_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mommodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mom_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
