# Generated by Django 3.1.5 on 2021-01-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0019_auto_20210129_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
