# Generated by Django 3.1.5 on 2021-01-29 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0020_auto_20210129_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committeereportordinancemodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cro_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committeereportresolutionmodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='crr_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mommodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mom_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolutionmodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
