# Generated by Django 3.1.2 on 2021-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0025_messagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
