# Generated by Django 3.1.5 on 2021-02-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0026_messagesmodel_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesmodel',
            name='is_sent',
        ),
        migrations.CreateModel(
            name='SentMessagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_receiver_fk', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_sender_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
