# Generated by Django 3.1.2 on 2021-02-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0028_webexmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='webexmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webex_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
