# Generated by Django 3.1.5 on 2021-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0029_webexmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldDocumentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files/%Y/%m/%d')),
                ('name', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=250)),
                ('last_modified_date', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
    ]
