# Generated by Django 3.1.5 on 2021-02-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0030_olddocumentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddocumentsmodel',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
