# Generated by Django 3.1.5 on 2021-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0031_olddocumentsmodel_date_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olddocumentsmodel',
            old_name='extension',
            new_name='content_type',
        ),
    ]
