# Generated by Django 3.1.5 on 2021-02-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0032_auto_20210211_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olddocumentsmodel',
            name='last_modified_date',
        ),
    ]
