# Generated by Django 3.1.5 on 2021-03-30 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elegislative_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0033_remove_olddocumentsmodel_last_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOfBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='None', max_length=100)),
                ('is_signed', models.BooleanField(default=False)),
                ('hard_copy', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[elegislative_app.models.file_validator_pdf], verbose_name='hard copy')),
                ('content', models.TextField()),
                ('date_filed', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_of_business_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
